### ISSUE TITLE
Fav list

### ISSUE THREAD

**Issue by Nephos** [AuthCr/qt-auth-api#3]
Favorites connections

**Comment by Lucie-Dispot** [comment]
Added in 9e2bc8a03f91df196e130210653afb8caac48f49

**Comment by Lucie-Dispot** [comment]
To do : put the fav file in ~/.local/

**Comment by Lucie-Dispot** [comment]
Fixed in dc8ad55732b6aead2b0af5dab319ad3923a913c4
