### ISSUE TITLE
Log box

### ISSUE THREAD

**Issue by Nephos** [AuthCr/qt-auth-api#5]
Log queries / replies.
Also log in a 2snd tab some "clear information" (operations done by the user).
It should be possible to LOG everything in a file as security measure.

**Comment by Lucie-Dispot** [comment]
Added & fixed in e646d5494b3fed7762641d220efc102d25ae5f22, c20c434b02830d3e672c5327747edfcd021c3e2e

Tell me if there are improvements to be done.
